apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-pred-ml-kube
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: price-pred-ml-kube
  template:
    metadata:
      labels:
        app: price-pred-ml-kube
    spec:
      containers:
      - name: price-pred-ml-kube
        image: docker.io/hdingdockerdesktop/price-pred-ml-kube1:latest 
        ports:
        - containerPort: 8000
